Facetting
====================
A very useful kind of visualization technique is the small multiple. 
In a small multiple visualization, you create many of the same plot for multiple subsets of the data. 
ggplot2 has two ways to create small multiples: facet_wrap() and facet_grid().

<hr>
### Facet Wraps
- facet_wrap() creates and labels a plot for every level of a factor which is passed to it. 
- Its primary argument takes the form of a one sided formula: ~Factor. 
- It will then try to efficiently "wrap" these plots into a 2d grid.

<hr>
### Facet Scales

Usually you will want all of your facets to have the same x and y scales. If you're plotting the same data in each facet, having free scales on each of the facets will ruin comparability across facets. However, sometimes it will be appropriate to have free scales. For instance, when we plotted international data for men and women on a few different measures, it was necessary to have free scales. I did this by passing scales = "free" to facet_wrap().

```{r}
ggplot(data = gender.comp, aes(Male, Female))+
  geom_abline(colour = "grey80")+
  geom_point(alpha = 0.6)+
  facet_wrap(~Measure, scales = "free")
```  
