
#### {Adding lines}

Adding Lines to a Scatter Plot

Previously we have used scatter plots to plot bivariate data. They were constructed using the ``plot()`` command.  

<pre>
<code>

plot(mtcars$mpg,mtcars$wt,pch=18,col="red")
title("Cars Data Set",sub="MPG v Weight")

# Now to Add Lines
abline(v=mean(mtcars$mpg))
abline(h=mean(mtcars$wt))
abline(a=5,b=-1/6)
</code>
</pre>



\section{Adding titles, lines, points to plots}


\footnotesize <pre><code>
library(MASS)
# Colour points and choose plotting symbols according to a levels of a factor
plot(Cars93$Weight, Cars93$EngineSize, col=as.numeric(Cars93$Type),
pch=as.numeric(Cars93$Type))

# Adds x and y axes labels and a title.
plot(Cars93$Weight, Cars93$EngineSize, ylab="Engine Size",
xlab="Weight", main="My plot")
# Add lines to the plot.
lines(x=c(min(Cars93$Weight), max(Cars93$Weight)), y=c(min(Cars93$EngineSize),
max(Cars93$EngineSize)), lwd=4, lty=3, col="green")
abline(h=3, lty=2)
abline(v=1999, lty=4)
# Add points to the plot.
</code></pre>





#### Adding lines

Recall that we can use the arguments ``xlim`` and ``ylim`` to control the vertical and horizontal range of the plots, by specifying a two element vector (min and max) for each.


#### ``abline()``

Using the ``abline()`` command, we can add lines to our scatter plots. We specify the argument according to the type of line required. 
A demonstration of three types of line is provided below.

Additionally we change the colour of the added lines, by specifying a colour in the ``col`` argument. 

We can also change the line type to one of four possible types, using the ``lty`` argument.




### Adding a Regresion Line to a Plot

#### Adding the regression model line

The ``abline()`` function can be used to add a regression model line  by supplying as an argument the ``coef()`` values for intercept and slope estimates .These estimates can be inputted directly by using both functions in conjunction.


In regression models, scatterplots are often used to depict the relationship between the predictor variable ($x$) and a response variable ($y$).


<pre>
<code>
Fit1 = lm(mpg~wt,data=mtcars)
coef(Fit1)

#(Intercept)          wt 
#  37.285126   -5.344472 

plot(wt,mpg,pch=18,col="red")
abline(coef(Fit1))
</code>
</pre>










