R Graphics}

Enhancing your scatter plots
=============================================

### Adding lines
Previously we have used scatter plots to plot bivariate data. They were constructed using the plot() command.
Recall that we can use the arguments ``xlim} and ``ylim} to control the vertical and horizontal range of the plots, by specifying a two element vector (min and max) for each.

Using the ``abline()`` command, we can add lines to our scatter plots. We specify the argument according to the type of line required. A demonstration of three types of line is provided below.
Additionally we change the colour of the added lines, by specifying a colour in the ``col} argument. We can also change the line type to one of four possible types, using the ``lty} argument.

The line types are follows
\begin{itemize}
* ``lty =1}   Normal full line (default)
* ``lty =2}   Dashed line
* ``lty =3}   Dotted line
* ``lty =4}   Dash-dot line
\end{itemize}
\large <pre><code>
x=rnorm(10)
y=rnorm(10)
plot(x,y)
plot(x,y,xlim=c(-4,4),ylim=c(-4,4))
abline(v =0 , lty =2 )    # add a vertical dotted line (here the y-axis) to the plot
abline(h=0  ,lty =3)    # add a horizontal dotted line (here the x-axis) to the plot
abline(a=0,b=1,col="green") # add a line to your plot with intercept "a" and slope "b"
</code></pre>\large

