<p>
### {Histograms}
Histograms can be created using the texttt{hist()} command.
To create a histogram of the car weights from the Cars93 data set

begin{myindentpar}{1cm}
<code>
hist(mtcars$mpg, main="Histogram of MPG (Data: MTCARS) ")
</code>

texttt{R} automatically chooses the number and width of the bars. We can
change this by specifying the location of the break points.

begin{myindentpar}{1cm}
<code>hist(Cars93$Weight, breaks=c(1500, 2050, 2300, 2350, 2400,
2500, 3000, 3500, 3570, 4000, 4500), xlab="Weight",
main="Histogram of Weight")
</code>




<p>
### {Boxplot}
Boxplots can be used to identify outliers.

By default, the texttt{boxplot()} command sets the orientation as vertical. By adding the argument texttt{horizontal=TRUE}, the orientation can be changed to horizontal.

begin{myindentpar}{1cm}
<code>
boxplot(mtcars$mpg, horizontal=TRUE, xlab="Miles Per Gallon",
main="Boxplot of MPG")
</code>


begin{figure}
  % Requires usepackage{graphicx}
  includegraphics[scale=0.4]{MTCARSboxplot.png}
  caption{Boxplot}label{boxplot}
end{figure}

